#!/usr/bin/env npx tsx

import { input, confirm } from "@inquirer/prompts";
import chalk from "chalk";
import { execSync } from "child_process";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve } from "path";

// ─── Types ──────────────────────────────────────────────

interface EnvVars {
  [key: string]: string;
}

interface ConvexEnvSync {
  key: string;
  value: string;
}

// ─── Helpers ────────────────────────────────────────────

const ENV_PATH = resolve(process.cwd(), ".env.local");

function parseEnvFile(path: string): EnvVars {
  if (!existsSync(path)) return {};
  const content = readFileSync(path, "utf-8");
  const vars: EnvVars = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    const value = trimmed.slice(eqIndex + 1).trim();
    vars[key] = value;
  }
  return vars;
}

function writeEnvFile(path: string, vars: EnvVars) {
  const sections: { header: string; keys: string[] }[] = [
    {
      header: "Convex Backend",
      keys: ["NEXT_PUBLIC_CONVEX_URL", "CONVEX_DEPLOYMENT"],
    },
    {
      header: "Clerk Authentication",
      keys: [
        "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
        "CLERK_SECRET_KEY",
        "CLERK_WEBHOOK_SECRET",
      ],
    },
    {
      header: "App Configuration",
      keys: [
        "NEXT_PUBLIC_APP_NAME",
        "NEXT_PUBLIC_APP_URL",
        "NEXT_PUBLIC_ENV",
      ],
    },
    {
      header: "Domain & Email",
      keys: ["EMAIL_DOMAIN", "SUPPORT_EMAIL"],
    },
    {
      header: "Resend Email",
      keys: ["RESEND_API_KEY"],
    },
    {
      header: "Lemon Squeezy Payments",
      keys: [
        "LEMONSQUEEZY_API_KEY",
        "LEMONSQUEEZY_STORE_ID",
        "NEXT_PUBLIC_LEMONSQUEEZY_STANDARD_VARIANT_ID",
        "NEXT_PUBLIC_LEMONSQUEEZY_BUNDLE_VARIANT_ID",
        "LEMONSQUEEZY_WEBHOOK_SECRET",
      ],
    },
    {
      header: "PostHog Analytics",
      keys: ["NEXT_PUBLIC_POSTHOG_KEY"],
    },
    {
      header: "Meta Pixel",
      keys: [
        "NEXT_PUBLIC_META_PIXEL_ID",
        "META_CONVERSION_API_ACCESS_TOKEN",
        "META_API_VERSION",
      ],
    },
    {
      header: "Blog Webhook",
      keys: ["WEBHOOK_API_KEY"],
    },
  ];

  const written = new Set<string>();
  const lines: string[] = [
    "# ============================================",
    "# Environment Variables (generated by npm run setup)",
    "# ============================================",
    "",
  ];

  for (const section of sections) {
    const sectionVars = section.keys.filter((k) => vars[k]);
    if (sectionVars.length === 0) continue;

    lines.push(`# ${section.header}`);
    for (const key of sectionVars) {
      lines.push(`${key}=${vars[key]}`);
      written.add(key);
    }
    lines.push("");
  }

  // Write any remaining vars not covered by sections
  const remaining = Object.keys(vars).filter((k) => !written.has(k) && vars[k]);
  if (remaining.length > 0) {
    lines.push("# Other");
    for (const key of remaining) {
      lines.push(`${key}=${vars[key]}`);
    }
    lines.push("");
  }

  writeFileSync(path, lines.join("\n"));
}

function getSiteUrl(convexUrl: string): string {
  return convexUrl.replace(".convex.cloud", ".convex.site");
}

function heading(text: string) {
  console.log(`\n${chalk.bold.cyan("─── " + text + " ───")}\n`);
}

function link(url: string) {
  return chalk.underline.blue(url);
}

function hint(text: string) {
  return chalk.dim(text);
}

// ─── Main ───────────────────────────────────────────────

async function main() {
  console.log(
    chalk.bold(`
┌──────────────────────────────────────┐
│       SaaS Starter Kit Setup         │
└──────────────────────────────────────┘
`)
  );
  console.log(
    "This wizard walks you through configuring your environment.\nRequired services: Convex + Clerk. Everything else is optional.\n"
  );

  // Load existing env
  const env = parseEnvFile(ENV_PATH);
  const convexSync: ConvexEnvSync[] = [];
  const configured: string[] = [];
  const skipped: string[] = [];

  // ─── Step 1: Convex ──────────────────────────────────

  heading("Convex (backend)");

  if (env.NEXT_PUBLIC_CONVEX_URL) {
    console.log(
      `${chalk.green("✓")} Already configured: ${hint(env.NEXT_PUBLIC_CONVEX_URL)}`
    );
    const reconfigure = await confirm({
      message: "Reconfigure Convex?",
      default: false,
    });
    if (!reconfigure) {
      configured.push("Convex");
    } else {
      console.log(
        `\nRunning ${chalk.bold("npx convex dev --once")}... Follow the prompts.\n`
      );
      try {
        execSync("npx convex dev --once", { stdio: "inherit" });
      } catch {
        console.log(
          chalk.yellow(
            "\nConvex setup had an issue. You can run `npx convex dev` manually later."
          )
        );
      }
      // Re-read env since convex CLI writes to .env.local
      Object.assign(env, parseEnvFile(ENV_PATH));
      configured.push("Convex");
    }
  } else {
    console.log(
      `This will create your Convex project and set ${chalk.bold("NEXT_PUBLIC_CONVEX_URL")}.\n`
    );
    console.log(
      `Running ${chalk.bold("npx convex dev --once")}... Follow the prompts.\n`
    );
    try {
      execSync("npx convex dev --once", { stdio: "inherit" });
    } catch {
      console.log(
        chalk.yellow(
          "\nConvex setup had an issue. You can run `npx convex dev` manually later."
        )
      );
    }
    // Re-read env since convex CLI writes to .env.local
    Object.assign(env, parseEnvFile(ENV_PATH));
    configured.push("Convex");
  }

  const siteUrl = env.NEXT_PUBLIC_CONVEX_URL
    ? getSiteUrl(env.NEXT_PUBLIC_CONVEX_URL)
    : null;

  // ─── Step 2: Clerk ───────────────────────────────────

  heading("Clerk (authentication)");
  console.log(`Get your keys at: ${link("https://clerk.com")}`);
  console.log(hint("Go to your app → API Keys\n"));

  env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = await input({
    message: "Clerk Publishable Key:",
    default: env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY || undefined,
    required: true,
  });

  env.CLERK_SECRET_KEY = await input({
    message: "Clerk Secret Key:",
    default: env.CLERK_SECRET_KEY || undefined,
    required: true,
  });

  if (siteUrl) {
    console.log(`\n${chalk.bold("Webhook setup:")}`);
    console.log(
      `  1. Go to ${link("https://clerk.com")} → Webhooks → Add Endpoint`
    );
    console.log(`  2. URL: ${chalk.bold(`${siteUrl}/clerk-webhook`)}`);
    console.log(
      `  3. Subscribe to: ${chalk.bold("user.created, user.updated, user.deleted")}`
    );
    console.log("  4. Copy the Signing Secret below\n");
  }

  env.CLERK_WEBHOOK_SECRET = await input({
    message: "Clerk Webhook Secret:",
    default: env.CLERK_WEBHOOK_SECRET || undefined,
    required: true,
  });

  convexSync.push({
    key: "CLERK_WEBHOOK_SECRET",
    value: env.CLERK_WEBHOOK_SECRET,
  });
  configured.push("Clerk");

  // ─── Step 3: App Config ──────────────────────────────

  heading("App Configuration");

  env.NEXT_PUBLIC_APP_NAME = await input({
    message: "App name:",
    default: env.NEXT_PUBLIC_APP_NAME || "My App",
  });

  env.NEXT_PUBLIC_APP_URL = await input({
    message: "App URL:",
    default: env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  });

  env.NEXT_PUBLIC_ENV = env.NEXT_PUBLIC_ENV || "dev";
  configured.push("App Config");

  // ─── Step 4: Domain & Email (optional) ───────────────

  heading("Domain & Email (optional)");
  console.log(hint("Used for Resend email sending domain and support address.\n"));

  const setupDomain = await confirm({
    message: "Configure domain & email?",
    default: false,
  });

  if (setupDomain) {
    env.EMAIL_DOMAIN = await input({
      message: "Email domain (e.g. myapp.com):",
      default: env.EMAIL_DOMAIN || undefined,
      required: true,
    });

    env.SUPPORT_EMAIL = await input({
      message: "Support email:",
      default: env.SUPPORT_EMAIL || `support@${env.EMAIL_DOMAIN}`,
    });
    configured.push("Domain & Email");
  } else {
    skipped.push("Domain & Email");
  }

  // ─── Step 5: Resend (optional) ───────────────────────

  heading("Resend (optional)");
  console.log(`Email sending service: ${link("https://resend.com")}`);
  console.log(hint("Go to API Keys → Create API Key\n"));

  const setupResend = await confirm({
    message: "Configure Resend?",
    default: false,
  });

  if (setupResend) {
    env.RESEND_API_KEY = await input({
      message: "Resend API Key:",
      default: env.RESEND_API_KEY || undefined,
      required: true,
    });

    convexSync.push({ key: "RESEND_API_KEY", value: env.RESEND_API_KEY });
    configured.push("Resend");
  } else {
    skipped.push("Resend");
  }

  // ─── Step 6: Lemon Squeezy (optional) ────────────────

  heading("Lemon Squeezy (optional)");
  console.log(`Payment processing: ${link("https://lemonsqueezy.com")}`);
  console.log(hint("Go to Settings → API → Create API Key\n"));

  const setupLemon = await confirm({
    message: "Configure Lemon Squeezy?",
    default: false,
  });

  if (setupLemon) {
    env.LEMONSQUEEZY_API_KEY = await input({
      message: "API Key:",
      default: env.LEMONSQUEEZY_API_KEY || undefined,
      required: true,
    });

    env.LEMONSQUEEZY_STORE_ID = await input({
      message: "Store ID:",
      default: env.LEMONSQUEEZY_STORE_ID || undefined,
      required: true,
    });

    env.NEXT_PUBLIC_LEMONSQUEEZY_STANDARD_VARIANT_ID = await input({
      message: "Standard variant ID:",
      default:
        env.NEXT_PUBLIC_LEMONSQUEEZY_STANDARD_VARIANT_ID || undefined,
    });

    env.NEXT_PUBLIC_LEMONSQUEEZY_BUNDLE_VARIANT_ID = await input({
      message: "Bundle variant ID:",
      default: env.NEXT_PUBLIC_LEMONSQUEEZY_BUNDLE_VARIANT_ID || undefined,
    });

    if (siteUrl) {
      console.log(
        `\n${chalk.bold("Webhook setup:")}`
      );
      console.log(
        `  1. Go to ${link("https://app.lemonsqueezy.com")} → Settings → Webhooks`
      );
      console.log(
        `  2. Callback URL: ${chalk.bold(`${siteUrl}/lemonsqueezy-webhook`)}`
      );
      console.log("  3. Copy the Signing Secret below\n");
    }

    env.LEMONSQUEEZY_WEBHOOK_SECRET = await input({
      message: "Webhook Secret:",
      default: env.LEMONSQUEEZY_WEBHOOK_SECRET || undefined,
    });

    convexSync.push({
      key: "LEMONSQUEEZY_API_KEY",
      value: env.LEMONSQUEEZY_API_KEY,
    });
    convexSync.push({
      key: "LEMONSQUEEZY_STORE_ID",
      value: env.LEMONSQUEEZY_STORE_ID,
    });
    if (env.LEMONSQUEEZY_WEBHOOK_SECRET) {
      convexSync.push({
        key: "LEMONSQUEEZY_WEBHOOK_SECRET",
        value: env.LEMONSQUEEZY_WEBHOOK_SECRET,
      });
    }
    configured.push("Lemon Squeezy");
  } else {
    skipped.push("Lemon Squeezy");
  }

  // ─── Step 7: PostHog (optional) ──────────────────────

  heading("PostHog (optional)");
  console.log(`Product analytics: ${link("https://posthog.com")}`);
  console.log(hint("Go to Project Settings → Project API Key\n"));

  const setupPostHog = await confirm({
    message: "Configure PostHog?",
    default: false,
  });

  if (setupPostHog) {
    env.NEXT_PUBLIC_POSTHOG_KEY = await input({
      message: "PostHog Project API Key:",
      default: env.NEXT_PUBLIC_POSTHOG_KEY || undefined,
      required: true,
    });
    configured.push("PostHog");
  } else {
    skipped.push("PostHog");
  }

  // ─── Step 8: Meta Pixel (optional) ───────────────────

  heading("Meta Pixel (optional)");
  console.log(
    `Conversion tracking: ${link("https://business.facebook.com/events_manager")}`
  );
  console.log(hint("Go to Events Manager → Data Sources → Your Pixel\n"));

  const setupMeta = await confirm({
    message: "Configure Meta Pixel?",
    default: false,
  });

  if (setupMeta) {
    env.NEXT_PUBLIC_META_PIXEL_ID = await input({
      message: "Pixel ID:",
      default: env.NEXT_PUBLIC_META_PIXEL_ID || undefined,
      required: true,
    });

    env.META_CONVERSION_API_ACCESS_TOKEN = await input({
      message: "Conversion API Access Token:",
      default: env.META_CONVERSION_API_ACCESS_TOKEN || undefined,
    });

    env.META_API_VERSION = env.META_API_VERSION || "v22.0";
    configured.push("Meta Pixel");
  } else {
    skipped.push("Meta Pixel");
  }

  // ─── Write .env.local ────────────────────────────────

  heading("Writing .env.local");
  writeEnvFile(ENV_PATH, env);
  console.log(`${chalk.green("✓")} Saved to ${chalk.bold(".env.local")}`);

  // ─── Sync Convex env vars ────────────────────────────

  if (convexSync.length > 0) {
    heading("Syncing Convex environment variables");
    for (const { key, value } of convexSync) {
      if (!value) continue;
      try {
        execSync(`npx convex env set ${key} "${value}"`, {
          stdio: "pipe",
        });
        console.log(`  ${chalk.green("✓")} ${key}`);
      } catch {
        console.log(
          `  ${chalk.yellow("!")} ${key} — failed. Set it manually: npx convex env set ${key} <value>`
        );
      }
    }
  }

  // ─── Summary ─────────────────────────────────────────

  console.log(
    chalk.bold(`
┌──────────────────────────────────────┐
│            Setup Complete            │
└──────────────────────────────────────┘
`)
  );

  if (configured.length > 0) {
    console.log(chalk.green("  Configured:"));
    for (const item of configured) {
      console.log(`    ${chalk.green("✓")} ${item}`);
    }
  }

  if (skipped.length > 0) {
    console.log(chalk.dim("\n  Skipped (configure anytime with npm run setup):"));
    for (const item of skipped) {
      console.log(`    ${chalk.dim("○")} ${item}`);
    }
  }

  console.log(`\n${chalk.bold("Next steps:")}`);
  console.log(`  ${chalk.cyan("npx convex dev")}     ${hint("# Terminal 1: Convex backend")}`);
  console.log(`  ${chalk.cyan("npm run dev")}        ${hint("# Terminal 2: Next.js frontend")}`);
  console.log("");
}

main().catch((err) => {
  if (err.name === "ExitPromptError") {
    console.log(chalk.dim("\nSetup cancelled."));
    process.exit(0);
  }
  console.error(chalk.red("\nSetup failed:"), err);
  process.exit(1);
});
